# Generated by Django 3.2 on 2021-12-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_router', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missedcall',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
